language: ruby

rvm:
  - 2.4.0

addons:
  postgresql: "9.4"

service:
  - postgresql

before_install:
  - gem install bundler

install:
  - bundle install

before_script:
  - RAILS_ENV=test bundle exec rails db:create
  - RAILS_ENV=test bundle exec rails db:migrate

script:
  - bundle exec rspec
